### ISSUE TITLE
Ezt a parancsot jobban nem lehetne optimalizálni?

### ISSUE THREAD

**Issue by andris155** [TryHardDood/myZone#14]
![kepkivagas](https://cloud.githubusercontent.com/assets/8324198/23039299/6537ea22-f48d-11e6-8d35-36ed9ea1d110.PNG)

**Comment by benjaminforras** [comment]
Köszi, hogy jelezted. Így remélhetőleg gyorsabban fog lefutni a parancs.

**Download**: https://github.com/TryHardDood/myZone/releases/tag/v1.1.154-SNAPSHOT
**Commit**: https://github.com/TryHardDood/myZone/commit/eecdcd9fabce6e5ac9eee4cfe639102fc71f8bc4

**Comment by andris155** [comment]
Jaj csak megint nem tudom plugmannal berakni. :/

**Comment by andris155** [comment]
Ha berakom az update mappába akkor magától frissíti?, mert 50 játékossal nem akarok újraindítást,

**Comment by benjaminforras** [comment]
Sajnos nem tudom

**Comment by andris155** [comment]
Mind1 majd megoldom. Köszönjük.
