### ISSUE TITLE
notify-enter ezt hogy kellene akkor? Ez lenne title nem?

### ISSUE THREAD

**Issue by andris155** [TryHardDood/myZone#15]
GUI-val is ezt írja.
![kepkivagas](https://cloud.githubusercontent.com/assets/8324198/23073505/208de58a-f536-11e6-9d6c-c01f38e7d225.PNG)

**Comment by benjaminforras** [comment]
https://worldguard.enginehub.org/en/latest/regions/flags/#miscellaneous

**Comment by andris155** [comment]
köszi
