### ISSUE TITLE
Lehetnének skines fejek, a zóna tulajnál és tagoknál meg az adott játékos skines feje

### ISSUE THREAD

**Issue by andris155** [TryHardDood/myZone#16]
![kepkivagas](https://cloud.githubusercontent.com/assets/8324198/23073563/48c410b0-f536-11e6-89e6-e3603815c8d6.PNG)
![kepkivagas](https://cloud.githubusercontent.com/assets/8324198/23073582/5692648a-f536-11e6-8b7d-8b9b28bdaa5d.PNG)

**Comment by andris155** [comment]
Nem működik sajnos. :(

**Comment by benjaminforras** [comment]
Kitudnád próbálni?
Letöltés: https://github.com/TryHardDood/myZone/releases/tag/v1.1.165-SNAPSHOT

Commit: https://github.com/TryHardDood/myZone/commit/9df736646b790d90ea0c2e2e24b977b5e6153e9c

**Comment by andris155** [comment]
A v1.1.166-SNAPSHOT-al nem működött.

**Comment by benjaminforras** [comment]
Offline módban van a szerver?

**Comment by andris155** [comment]
Abban.

**Comment by benjaminforras** [comment]
Akkor valószínűleg azért nem működik.

**Comment by andris155** [comment]
De ettől vannak fej skinek. Sőt van olyan plugin is a szerveren amiben GUI-s menü van és abban is vannak fej skinek.

**Comment by benjaminforras** [comment]
Nyílt forráskódú az a plugin?
Ha igen akkor rápillantanék.

**Comment by andris155** [comment]
Heads plugin. Mivel fizetős nem hiszem, hogy az lenne. De van több ilyen Heads plugin is ingyen is valamelyik lehet nyílt forráskódú.
