### ISSUE TITLE
Szerintem nem fér ki minden flag tábla egy oldalra.

### ISSUE THREAD

**Issue by andris155** [TryHardDood/myZone#18]
![kepkivagas](https://cloud.githubusercontent.com/assets/8324198/23073680/9fd4f342-f536-11e6-8d68-ac493faa7b76.PNG)

**Comment by benjaminforras** [comment]
Javítva: https://github.com/TryHardDood/myZone/commit/e4735013772ab7c1024ee2a4a2e5e03028e3e78a

**Comment by andris155** [comment]
köszi
