### ISSUE TITLE
Hogyan lehet törölni a greeting és farewell flaget?

### ISSUE THREAD

**Issue by andris155** [TryHardDood/myZone#20]
A none nem működik.

**Comment by benjaminforras** [comment]
Próbáld meg úgy, hogy nem írsz értéket.
**/zone flag \<zone\> \<flag\>**

Edit: Nekem működik none értékkel is

**Comment by andris155** [comment]
/zone flag zóna greeting ide beírok egy szöveget az oké, de ha azt írom ide none akkor nem törli a flagot.

**Comment by benjaminforras** [comment]
Próbáld meg úgy, hogy **nem írsz értéket**.
**Tehát:** /zone flag \<zone\> \<flag\>
