### ISSUE TITLE
3 kapcsolós táblák a menüben

### ISSUE THREAD

**Issue by andris155** [TryHardDood/myZone#22]
allow - deny - none

**Comment by benjaminforras** [comment]
Ezeket tartalmazza alapból.
Vagy mit szeretnél?

**Comment by andris155** [comment]
Nekem csak allow, és deny között kapcsol. Azt szeretném, hogy az első klikk a táblára deny-re, a 2. allow-ra állítsa, majd a 3. none-ra állítsa a flagot.

**Comment by benjaminforras** [comment]
Jobb kattintással kikapcsolja az adott flag-et.

**Comment by andris155** [comment]
köszi
