### ISSUE TITLE
Hibás szöveg

### ISSUE THREAD

**Issue by andris155** [TryHardDood/myZone#23]
![kepkivagas](https://cloud.githubusercontent.com/assets/8324198/23096534/2386a13e-f61f-11e6-972d-37205fddf69c.PNG)

**Comment by benjaminforras** [comment]
Amennyiben a meglévő magyar fordítást szeretnéd használni a következő sort írd át:
`flag_reset_success = &aSikeresen visszaállítottad a '&c{0}&a' flag-et.`
Erre:
`flag_reset_success = &aSikeresen visszaállítottad a \'&c{0}&a\' flag-et.`

**Comment by andris155** [comment]
Kicseréltem a fájlt de így is ezt írja. Vagy a /zone reload nem tölti be?

**Comment by benjaminforras** [comment]
Esetleg próbáld meg így. 
A /zone reload paranccsal működnie kell. 
`flag_reset_success = &aSikeresen visszaállítottad a &c{0}&a flag-et.`

**Comment by andris155** [comment]
Ez működik, köszi!
