### ISSUE TITLE
Nem működik az enderpearl tiltás flag a WorldGaurdban ha berakom a plugint.

### ISSUE THREAD

**Issue by andris155** [TryHardDood/myZone#25]

**Comment by benjaminforras** [comment]
Egész biztos, hogy ez a plugin okozza a problémát?
Semmilyen utalás nincs enderpearl-ekre a pluginban, így érthetetlenül állok ez előtt.

**Comment by andris155** [comment]
Igen 100%. Ha kiszedem egyből működik a tiltás. Ha bent van a plugin akkor csak a tiltó szöveget írja, de ugyan úgy teleportál.

**Comment by andris155** [comment]
Ezt írja, de a pluginnal sajnos ennek ellenére is teleportál.
![kepkivagas](https://cloud.githubusercontent.com/assets/8324198/23814680/b7c8b060-05e4-11e7-9051-0c807e87e9c6.PNG)

**Comment by benjaminforras** [comment]
**Javítva.**
_Köszönöm, hogy jelezted._

Letöltés: [v1.1.167-SNAPSHOT](https://github.com/TryHardDood/myZone/releases/tag/v1.1.167-SNAPSHOT)

**Comment by andris155** [comment]
köszönjük!
