### ISSUE TITLE
Néhány zónát nem enged törölni

### ISSUE THREAD

**Issue by andris155** [TryHardDood/myZone#3]
Néhány zónát nem töröl egyszerűen nem ír semmit a parancsra azt se, hogy nem törölhető, meg semmit. A védés pedig megvan WG-ben is tehát nem hibás védésről lenne szó. A konzolban sem ír egyébként hibát.

Az egyik nem törölhető védés:
KariFa.yml:
OwnerID: 8c5d0ec0-29b3-3245-9c06-5a41438bacbd
ZoneName: KariFa
RegionID: 8c5d0ec0-29b3-3245-9c06-5a41438bacbd_185

regions.yml:
   8c5d0ec0-29b3-3245-9c06-5a41438bacbd_185:
        min: {x: 1156.0, y: 68.0, z: 1923.0}
        max: {x: 1170.0, y: 97.0, z: 1937.0}
        members:
            unique-ids: [cc0ab670-5383-3057-a6db-c596cd8666a0]
        flags: {}
        owners:
            unique-ids: [8c5d0ec0-29b3-3245-9c06-5a41438bacbd]
        type: cuboid
        priority: 0

**Comment by benjaminforras** [comment]
Paranccsal vagy a menün keresztül próbálod törölni a zónát?

**Comment by andris155** [comment]
Én paranccsal próbáltam, de szerintem valószínűleg menüvel sem megy.

**Comment by benjaminforras** [comment]
Javítva: https://github.com/TryHardDood/myZone/commit/e4761cbf696a161d2e18aac1bd8cb330f9889d6a
