### ISSUE TITLE
null helyett jobb lenne valami más szöveg

### ISSUE THREAD

**Issue by andris155** [TryHardDood/myZone#30]
## What steps will reproduce the problem?  
1. Jobb klikk fakardal egy nem zóna WorldGaurd védésre.

## What were you expecting to happen? What happened instead?  
Jó lenne ha null helyett azt írná, hogy Ezt a zónát WorldGuard-al védték le vagy valami hasonló. Vagy még jobb lenne, ha felismerné, hogy az nem zóna és a sima WorldGuard régió nevét írná ki így WorldGuard védés: védés neve.

## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
![kepkivagas](https://user-images.githubusercontent.com/8324198/29048913-711b1c88-7bd3-11e7-9bf1-05ba7191ec9b.PNG)

## What Spigot version are you using? *Type /version*  
![kepkivagas](https://user-images.githubusercontent.com/8324198/29048926-846f7b9e-7bd3-11e7-8b20-83ef3fd73bd9.PNG)

## What plugins are you using? *Type /plugins*  
Elküldöm, ha szükséges.

## Additional information?  *(Did it work in previous versions? etc.)*
![kepkivagas](https://user-images.githubusercontent.com/8324198/29048948-9d5e8ffa-7bd3-11e7-9ca0-5e955be2487a.PNG)

**Comment by ghost** [comment]
Ez tényleg jó lenne.
