### ISSUE TITLE
1.13 frissítés

### ISSUE THREAD

**Issue by andris155** [TryHardDood/myZone#32]
1.13-ra és a WorldGuard 7-es verzióra lesz frissítve a plugin?

**Comment by benjaminforras** [comment]
Jelenleg még nincs kész a WorldGuard 7-es verziója, addig felesleges frissíteni.

**Comment by andris155** [comment]
http://builds.enginehub.org/job/worldguard?branch=string-ids

**Comment by benjaminforras** [comment]
> Be aware that this branch (string-ids) is not the main branch (master)!
> 
> Branches other than the main one may be experimental. In addition, you should be using stable releases rather than these test builds.

Attól hogy elérhetőek a test build-ek nem jelenti azt hogy elkészültek. Több nagyobb változás is történt 2 build között, köztük az is, ami miatt nem működik a myzone a worldguard 1.13-as verziójával

**Comment by andris155** [comment]
Rendben.
