### ISSUE TITLE
Nem lehet levenni a flagokat, csak ki/be kapcsolni

### ISSUE THREAD

**Issue by andris155** [TryHardDood/myZone#5]
Nagyon jó lenne egy olyan lehetőség a GUI-ba és a parancsba, hogy törölni is lehessen a flagokat a zónáról. Gyakran volt már olyan, hogy véletlen hozzáadtak valamit majd után le akarták szedni mivel csak úgy nem vonatkozik azokra akik a zónához vannak adva.

**Comment by benjaminforras** [comment]
Mostantól a menüt használva **jobb klikkel lehet visszaállítani** a flag-eket, illetve paranccsal: **/zone flag \<zone\> \<flag\> none**

From v1.1 you can reset the flags by right clicking the flags in the GUI or entering the following command: **/zone flag \<zone\> \<flag\> none**

**Comment by andris155** [comment]
Köszönjük :)
