### ISSUE TITLE
A nagyság beállítás nekem nem működik.

### ISSUE THREAD

**Issue by andris155** [TryHardDood/myZone#6]
Alapból ugye ez van beállítva:
(50, 256, 50): myzone.zone.max-size.1
Ez oké működik is.
(80, 256, 80): myzone.zone.max-size.2
ez viszont már nem működik hiába adom meg rá a jogot, és veszem el az 1-s jogot. Mi lehet a gond?
így van megadva a rangnál:
- -myzone.zone.max-size.1
- myzone.zone.max-size.2

**Comment by benjaminforras** [comment]
Kérlek próbáld ki a legfrissebb [v1.1-SNAPSHOT](https://github.com/TryHardDood/myZone/releases/tag/v1.1-SNAPSHOT) verzióval.

**Comment by andris155** [comment]
Működik, Köszönjük!!
