### ISSUE TITLE
mvn-el nem lehet összerakni az 1.1-es verziót

### ISSUE THREAD

**Issue by andris155** [TryHardDood/myZone#7]
plusz a frissítést jó lenne ha valahogy ki lehetne kapcsolni, mert biztos megint bugos lesz ezzel a verzióval és megint töltegetni fogja mindig az ,,új" verziót.

**Comment by benjaminforras** [comment]
https://github.com/TryHardDood/myZone/releases/tag/v1.1

**Comment by andris155** [comment]
köszönjük :)
